name: PR Preview Cleanup

on:
  pull_request:
    types: [closed, locked]

permissions:
  contents: read
  packages: write
  pull-requests: read

env:
  REGISTRY: ghcr.io
  FRONTEND_IMAGE_NAME: ${{ vars.REPOSITORY_OWNER }}/frontend-preview
  BACKEND_IMAGE_NAME: ${{ vars.REPOSITORY_OWNER }}/backend-preview
  GCP_PROJECT_ID: ${{ vars.GCP_PROJECT_ID }} # qualified-gist-454616-m5
  GCP_REGION: ${{ vars.GCP_REGION }} # europe-west3

jobs:
  cleanup:
    name: Cleanup Preview Environment
    runs-on: ubuntu-latest

    steps:
      - name: Get preview ID
        id: preview-id
        run: echo "id=pr-${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Google Cloud SDK
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCLOUD_CREDENTIALS_KEY }}
          service_account: ${{ env.GCP_SERVICE_ACCOUNT }}
          export_environment_variables: true

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Delete Cloud Run services
        run: |
          gcloud run services delete frontend-${{ steps.preview-id.outputs.id }} \
            --region=${{ env.GCP_REGION }} \
            --quiet || true

          gcloud run services delete backend-${{ steps.preview-id.outputs.id }} \
            --region=${{ env.GCP_REGION }} \
            --quiet || true

      - name: Delete Docker images
        run: |
          gcloud container images delete ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE_NAME }}:${{ steps.preview-id.outputs.id }} \
            --quiet || true

          gcloud container images delete ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE_NAME }}:${{ steps.preview-id.outputs.id }} \
            --quiet || true

      - name: Cleanup Database and VPC
        run: |
          chmod +x .ci/cleanup-database.sh
          .ci/cleanup-database.sh ${{ github.event.pull_request.number }}
